blank_issues_enabled: false

contact_links:
  - name: Need help?
    url: https://redirect.macmousefix.com/?target=mmf-guides-and-community
    about: View guides or ask the community
  - name: Bug report
    url: https://redirect.macmousefix.com/?target=mmf-feedback-bug-report
    about: Report a bug
  - name: Enhancement request
    url: https://redirect.macmousefix.com/?target=mmf-feedback-feature-request
    about: Suggest a new feature, UI changes, or other improvements
  - name: Free form feedback
    url: https://redirect.macmousefix.com/?target=mmf-feedback-other
    about: Write free form feedback
